"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TokenMeta = exports.Token = exports.State = exports.next = exports.Lines = exports.Lexer = exports.isWhitespace = exports.RE_WHITESPACE = exports.isNewline = exports.RE_NEWLINE = exports.StringInput = exports.Input = void 0;
var Input_1 = require("./Input");
Object.defineProperty(exports, "Input", { enumerable: true, get: function () { return Input_1.Input; } });
Object.defineProperty(exports, "StringInput", { enumerable: true, get: function () { return Input_1.StringInput; } });
var isNewline_1 = require("./isNewline");
Object.defineProperty(exports, "RE_NEWLINE", { enumerable: true, get: function () { return isNewline_1.RE_NEWLINE; } });
Object.defineProperty(exports, "isNewline", { enumerable: true, get: function () { return isNewline_1.isNewline; } });
var isWhitespace_1 = require("./isWhitespace");
Object.defineProperty(exports, "RE_WHITESPACE", { enumerable: true, get: function () { return isWhitespace_1.RE_WHITESPACE; } });
Object.defineProperty(exports, "isWhitespace", { enumerable: true, get: function () { return isWhitespace_1.isWhitespace; } });
var Lexer_1 = require("./Lexer");
Object.defineProperty(exports, "Lexer", { enumerable: true, get: function () { return Lexer_1.Lexer; } });
var Lines_1 = require("./Lines");
Object.defineProperty(exports, "Lines", { enumerable: true, get: function () { return Lines_1.Lines; } });
var next_1 = require("./next");
Object.defineProperty(exports, "next", { enumerable: true, get: function () { return next_1.next; } });
var State_1 = require("./State");
Object.defineProperty(exports, "State", { enumerable: true, get: function () { return State_1.State; } });
var Token_1 = require("./Token");
Object.defineProperty(exports, "Token", { enumerable: true, get: function () { return Token_1.Token; } });
var TokenMeta_1 = require("./TokenMeta");
Object.defineProperty(exports, "TokenMeta", { enumerable: true, get: function () { return TokenMeta_1.TokenMeta; } });
